import 'dart:math';

class Product {
  final String name;
  final String description;
  final String image;
  final int categoryId;

  Product({
    required this.name,
    required this.description,
    required this.image,
    required this.categoryId,
  });
}

class ProductCategory {
  int categoryId;
  String name;

  ProductCategory({
    required this.name,
    required this.categoryId,
  });
}

final List<ProductCategory> categories = [
  ProductCategory(
    categoryId: 0,
    name: "Cool cat Cool",
  ),
  ProductCategory(
    categoryId: 1,
    name: "Sad cat",
  ),
  ProductCategory(
    categoryId: 2,
    name: "Mad cat Mad",
  ),
  ProductCategory(
    categoryId: 3,
    name: "Bad cat",
  ),
  ProductCategory(
    categoryId: 4,
    name: "Sweet cat",
  ),
  ProductCategory(
    categoryId: 5,
    name: "WTF cat WTF",
  ),
];

String generateRandomString({int len = 10}) {
  var r = Random();
  return String.fromCharCodes(
      List.generate(len, (index) => r.nextInt(33) + 89));
}

final List<Product> items = [
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 0,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 0,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 0,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 0,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 0,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 0,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 0,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 0,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 1,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 2,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 3,
  ),
  Product(
      name: generateRandomString(),
      description: generateRandomString(len: 100),
      image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
      categoryId: 3),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 4,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
  Product(
    name: generateRandomString(),
    description: generateRandomString(len: 100),
    image: "https://loremflickr.com/320/240?random=${Random().nextInt(100)}",
    categoryId: 5,
  ),
];
